{
 "title": "Home Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Chickens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current egg count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"home_monitoring\"",
     "measure": "chicken_count_yolo",
     "rawQuery": "SELECT MAX(egg_sum.egg_count)\r\nFROM (\r\n  SELECT\r\n      time, measure_name, SUM(measure_value::double) as egg_count\r\n  FROM home_monitoring.metrics\r\n  WHERE time > ago(20m)\r\n      AND measure_name LIKE 'egg_count_blob'\r\n  GROUP BY time, measure_name\r\n) egg_sum",
     "table": "\"metrics\""
    }
   ]
  },
  {
   "title": "Eggs laid by algo and nesting box",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawQuery": "SELECT\r\n\tmeasure_name, \r\n  nesting_box,\r\n  CREATE_TIME_SERIES(time, measure_value::double) AS measure\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name LIKE 'egg_count_%'\r\nGROUP BY measure_name, nesting_box"
    }
   ]
  },
  {
   "title": "Chickens detected by nesting box",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawQuery": "SELECT\r\n    nesting_box,\r\n    CREATE_TIME_SERIES(time, measure_value::double) AS measure\r\nFROM home_monitoring.metrics\r\nWHERE time > ago(24h)\r\n\tAND measure_name = 'chicken_count_yolo'\r\nGROUP BY nesting_box"
    }
   ]
  },
  {
   "title": "Chicken coop temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawQuery": "SELECT\r\n\tCREATE_TIME_SERIES(time, measure_value::double * 1.8 + 32) AS measure\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='temperature'\r\n\tAND name='Chicken brooder'\r\n"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Indoor temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawQuery": "SELECT\r\n\tname,\r\n\tCREATE_TIME_SERIES(time, measure_value::double) AS measure\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='temperature'\r\n\tAND name='indoors'\r\nGROUP BY name\r\nORDER BY AVG(measure_value::double) DESC\r\n"
    },
    {
     "rawQuery": "SELECT\r\n\tname,\r\n\tCREATE_TIME_SERIES(time, measure_value::double * 1.8 + 32)  AS measure\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='temperature'\r\n\tAND name='Office temp'\r\nGROUP BY name\r\nORDER BY AVG(measure_value::double) DESC\r\n"
    }
   ]
  },
  {
   "title": "Refrigerator temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawQuery": "SELECT\r\n\tname,\r\n\tCREATE_TIME_SERIES(time, measure_value::double * 1.8 + 32)  AS measure\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='temperature'\r\n\tAND name='Fridge temp'\r\nGROUP BY name\r\nORDER BY AVG(measure_value::double) DESC\r\n"
    },
    {
     "rawQuery": "SELECT\r\n\tname,\r\n\tCREATE_TIME_SERIES(time, measure_value::double * 1.8 + 32)  AS measure\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='temperature'\r\n\tAND name='Freezer temp'\r\nGROUP BY name\r\nORDER BY AVG(measure_value::double) DESC\r\n"
    }
   ]
  },
  {
   "title": "Hot tub temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawQuery": "SELECT\r\n\tname,\r\n\tCREATE_TIME_SERIES(time, measure_value::double * 1.8 + 32)  AS measure\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='temperature'\r\n\tAND name='Hot Tub sensor'\r\nGROUP BY name\r\nORDER BY AVG(measure_value::double) DESC\r\n"
    }
   ]
  },
  { "title": "Garden", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Soil Moisture",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawQuery": "SELECT\r\n\tname,\r\n\tCREATE_TIME_SERIES(time, measure_value::double) AS measure\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='soil_moisture'\r\nGROUP BY name\r\nORDER BY AVG(measure_value::double) DESC\r\n"
    }
   ]
  },
  {
   "title": "Well tank water level",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT\r\n\tCREATE_TIME_SERIES(time, measure_value::double) AS measure\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='leak_sensor'\r\n"
    }
   ]
  },
  {
   "title": "Chicken water level",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT\r\n\tCREATE_TIME_SERIES(time, measure_value::double) AS measure\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='leak_sensor'\r\n\tAND name = 'chicken_water_sensor'\r\n"
    }
   ]
  },
  { "title": "Utilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Household water usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "gallons" } },
   "targets": [
    {
     "rawQuery": "SELECT\r\n\tCREATE_TIME_SERIES(time, measure_value::double) AS \"gallons used\"\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name = 'household_water_usage'\r\n"
    }
   ]
  },
  {
   "title": "Solar energy produced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawQuery": "SELECT\r\n\tbin(time, 1h), SUM(measure_value::double) / 1000 AS \"kWh\"\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name = 'solar_energy_produced'\r\nGROUP BY bin(time, 1h)\r\nORDER BY bin(time, 1h)"
    }
   ]
  },
  { "title": "Home network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "primary_residence ping timing",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "rawQuery": "SELECT\r\n\tname,\r\n\tCREATE_TIME_SERIES(time, measure_value::double) AS ping_min\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='ping_min'\r\nGROUP BY name\r\nORDER BY AVG(measure_value::double) DESC\r\n"
    },
    {
     "rawQuery": "SELECT\r\n\tname,\r\n\tCREATE_TIME_SERIES(time, measure_value::double) AS ping_avg\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='ping_avg'\r\nGROUP BY name\r\nORDER BY AVG(measure_value::double) DESC\r\n"
    },
    {
     "rawQuery": "SELECT\r\n\tname,\r\n\tCREATE_TIME_SERIES(time, measure_value::double) AS ping_max\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='ping_max'\r\nGROUP BY name\r\nORDER BY AVG(measure_value::double) DESC\r\n"
    }
   ]
  },
  {
   "title": "primary_residence ping packet loss",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "rawQuery": "SELECT\r\n\tname,\r\n\tCREATE_TIME_SERIES(time, measure_value::double) AS ping_packet_loss_pct\r\nFROM home_monitoring.metrics\r\nWHERE $__timeFilter\r\n\tAND measure_name='ping_packet_loss_pct'\r\nGROUP BY name\r\nORDER BY AVG(measure_value::double) DESC\r\n"
    }
   ]
  }
 ]
}